import { useState } from 'react';
import { BrowserRouter, Link, Route, Routes, useLocation } from 'react-router-dom';
import { Landmark, Menu, Wallet } from 'lucide-react';

const preview = <p className="notice" role="status">Preview content only — not live on-chain data, an NYC allocation, or proof of plan delivery.</p>;
function Header(){const[o,setO]=useState(false),l=useLocation();const n=[['/','Home'],['/rounds','Rounds'],['/history','History'],['/help','Help']];return <header><a className="brand" href="/"><Landmark/> MandateMesh</a><button className="menu" aria-label="Open navigation" aria-expanded={o} onClick={()=>setO(!o)}><Menu/></button><nav aria-label="Primary" className={o?'open':''}>{n.map(([to,x])=><Link className={l.pathname===to?'active':''} to={to} key={to}>{x}</Link>)}</nav><Link className="wallet" to="/account"><Wallet size={18}/>Connect wallet</Link></header>}
function Home(){return <><section className="hero"><p>Transparent planning allocation</p><h1>Fund plans, not private decisions.</h1><p>Validator consensus maps proposals to locked public mandates before capped GEN credits are available.</p><Link className="button" to="/rounds/new">Start a round</Link> <Link className="plain" to="/rounds">Explore rounds</Link></section>{preview}<section><h2>Three clear stages</h2><div className="grid"><article><b>1</b><h3>Lock context</h3><p>Fund a 2 GEN planning round around public mandate text.</p></article><article><b>2</b><h3>Invite plans</h3><p>Registered proposers submit one bounded planning proposal.</p></article><article><b>3</b><h3>Read result</h3><p>Only a complete coverage matrix can create credits.</p></article></div></section></>}
function Rounds(){return <><div className="title"><div><p>Rounds</p><h1>Find a planning round</h1></div><Link className="button" to="/rounds/new">Start a round</Link></div>{preview}<label>Search rounds<input aria-label="Search rounds" placeholder="Search by mandate or status"/></label><article className="card"><div><b>Accepting plans</b><h2>Skills and food access</h2><p>NYC CEC People’s Money · 2 GEN locked · Preview only</p></div><Link to="/rounds/preview-round">View round</Link></article></>}
function Start(){return <><h1>Start a transparent planning round</h1><p>Connection is required before any real transaction. Amounts are shown in GEN.</p><form><label>Round name<input required/></label><label>Public mandate source URL<input type="url" required/></label><label>Planning purse<input value="2 GEN" readOnly/></label><button className="button" disabled>Connect a wallet to create</button></form></>}
function Detail(){return <><h1>Skills and food access</h1>{preview}<div className="grid two"><article><h2>Locked mandate context</h2><p>Public mandate summaries appear here. The production adapter will load canonical views before showing allocations.</p></article><article><h2>What happens next</h2><ol><li>Plans close.</li><li>Validators review coverage.</li><li>Eligible credits appear after finality.</li></ol></article></div><Link className="button" to="/rounds/preview-round/propose">Submit a plan</Link></>}
function Propose(){return <><h1>Submit one focused plan</h1><form><label>Plan title<input required maxLength={90}/></label><label>How does it serve a locked mandate?<textarea required maxLength={1200} rows={7}/></label>{preview}<button className="button" disabled>Connect a wallet to submit</button></form></>}
function History(){return <><h1>Past allocations stay explainable</h1>{preview}<article className="empty"><h2>No canonical history connected</h2><p>A deployed contract is required before completed rounds and credits can be displayed.</p></article></>}
function Account(){return <><h1>Your wallet, your control</h1><article className="empty"><Wallet size={34}/><h2>No wallet connected</h2><p>The app will let you choose from detected EVM wallets; it never selects one for you.</p><button className="button" disabled>Wallet integration pending</button></article></>}
function Help(){return <><h1>What MandateMesh does — and does not do</h1><article className="card"><h2>What is decided?</h2><p>Validators assess proposal coverage of locked mandates, not whether a plan was completed or endorsed.</p><h2>When is GEN available?</h2><p>Only after finality and canonical state reload, never at wallet signature.</p></article></>}
function Shell(){return <><a className="skip" href="#main">Skip to content</a><Header/><main id="main"><Routes><Route path="/" element={<Home/>}/><Route path="/rounds" element={<Rounds/>}/><Route path="/rounds/new" element={<Start/>}/><Route path="/rounds/:id" element={<Detail/>}/><Route path="/rounds/:id/propose" element={<Propose/>}/><Route path="/history" element={<History/>}/><Route path="/account" element={<Account/>}/><Route path="/help" element={<Help/>}/></Routes></main></>};export default function App(){return <BrowserRouter><Shell/></BrowserRouter>}
