import { useEffect, useState, type FormEvent } from 'react';
import { BrowserRouter, Link, Route, Routes, useLocation } from 'react-router-dom';
import { GenLayerTransactionPanel } from '@genlayer/transaction-kit-react';
import { Landmark, Menu, Wallet, X } from 'lucide-react';
import { connectWallet, contractAddress, discoverWallets, readRound, type WalletChoice, useMandateKit } from './genlayer';

const twoGen = 2_000_000_000_000_000_000n;
function Header({ account, onWallet }: { account: string | null; onWallet: () => void }) { const [open, setOpen] = useState(false); const location = useLocation(); const nav = [['/', 'Home'], ['/rounds', 'Rounds'], ['/history', 'History'], ['/help', 'Help']]; return <header><a className="brand" href="/"><Landmark /> MandateMesh</a><button className="menu" aria-label="Open navigation" aria-expanded={open} onClick={() => setOpen(!open)}><Menu /></button><nav aria-label="Primary" className={open ? 'open' : ''}>{nav.map(([to, label]) => <Link className={location.pathname === to ? 'active' : ''} to={to} key={to}>{label}</Link>)}</nav><button className="wallet" onClick={onWallet}><Wallet size={18} />{account ? `${account.slice(0, 6)}…${account.slice(-4)}` : 'Connect wallet'}</button></header>; }
function WalletModal({ close, connected }: { close: () => void; connected: (choice: WalletChoice) => Promise<void> }) { const [wallets, setWallets] = useState<WalletChoice[]>([]); const [error, setError] = useState(''); useEffect(() => { discoverWallets().then(setWallets); }, []); return <div className="dialog-backdrop"><section className="dialog" role="dialog" aria-modal="true" aria-labelledby="wallet-title"><button className="icon" aria-label="Close wallet selection" onClick={close}><X /></button><h2 id="wallet-title">Choose a wallet</h2><p>MandateMesh requests Studio Dev before a write.</p>{wallets.length ? wallets.map((wallet) => <button className="wallet-choice" key={wallet.name} onClick={() => connected(wallet).catch((cause) => setError(cause.message || 'Connection failed.'))}>{wallet.name}</button>) : <p role="status">Searching for EVM wallet extensions…</p>}{error && <p className="error" role="alert">{error}</p>}</section></div>; }
function Home() { return <><section className="hero"><p>Transparent planning allocation</p><h1>Fund plans, not private decisions.</h1><p>Validator consensus maps proposals to locked public mandates before capped GEN credits are available.</p><Link className="button" to="/rounds/new">Start a round</Link> <Link className="plain" to="/rounds">Explore rounds</Link></section><section><h2>Three clear stages</h2><div className="grid"><article><b>1</b><h3>Lock context</h3><p>Fund a 2 GEN planning round around public mandates.</p></article><article><b>2</b><h3>Invite plans</h3><p>Registered proposers submit one bounded planning proposal.</p></article><article><b>3</b><h3>Read result</h3><p>Canonical state reloads after finality.</p></article></div></section></>; }
function Start({ provider, account }: { provider: WalletChoice['provider'] | null; account: `0x${string}` | null }) { const kit = useMandateKit(provider, account); const [roundId, setRoundId] = useState(''); const [people, setPeople] = useState(['', '', '']); const [proposalAt, setProposalAt] = useState(''); const [recoveryAt, setRecoveryAt] = useState(''); const [submitted, setSubmitted] = useState(false); const valid = !!kit && !!contractAddress && /^[a-z0-9-]{1,48}$/.test(roundId) && people.every((value) => /^0x[a-fA-F0-9]{40}$/.test(value)) && !!proposalAt && !!recoveryAt; const time = (value: string) => Math.floor(new Date(value).getTime() / 1000); return <><h1>Start a transparent planning round</h1><p>Creation locks exactly 2 GEN. The fee review comes from Studio Dev live policy.</p>{!contractAddress && <p className="error" role="alert">Contract configuration is missing; writes are disabled.</p>}<form onSubmit={(event: FormEvent) => { event.preventDefault(); if (valid) setSubmitted(true); }}><label>Round ID<input required value={roundId} onChange={(event) => setRoundId(event.target.value)} pattern="[a-z0-9-]+" /></label>{people.map((value, index) => <label key={index}>Proposer {index + 1} address<input required value={value} onChange={(event) => setPeople(people.map((person, cursor) => cursor === index ? event.target.value : person))} /></label>)}<label>Proposal deadline<input required type="datetime-local" value={proposalAt} onChange={(event) => setProposalAt(event.target.value)} /></label><label>Recovery deadline<input required type="datetime-local" value={recoveryAt} onChange={(event) => setRecoveryAt(event.target.value)} /></label><p>Planning purse: <strong>2 GEN</strong></p><button className="button" disabled={!valid}>{kit ? 'Review fee and create round' : 'Connect a wallet to create'}</button></form>{submitted && kit && contractAddress && <GenLayerTransactionPanel kit={kit} tx={{ kind: 'write', address: contractAddress, method: 'create_round', args: [roundId, ...people, time(proposalAt), time(recoveryAt)] }} userValue={twoGen} network="Studio Dev" trackUntil="finalized" onDone={() => readRound(roundId).catch(() => undefined)} />}</>; }
function RoundLookup() { const [id, setId] = useState(''); const [result, setResult] = useState(''); const [error, setError] = useState(''); return <form onSubmit={(event) => { event.preventDefault(); setError(''); readRound(id).then((value) => setResult(String(value))).catch((cause) => setError(cause.message)); }}><label>Round ID<input required value={id} onChange={(event) => setId(event.target.value)} /></label><button className="button" disabled={!contractAddress}>Load canonical state</button>{error && <p className="error" role="alert">{error}</p>}{result && <pre aria-live="polite">{result}</pre>}</form>; }
function Rounds() { return <><div className="title"><div><p>Rounds</p><h1>Read a canonical round</h1></div><Link className="button" to="/rounds/new">Start a round</Link></div><RoundLookup /></>; }
function History() { return <><h1>Past allocations stay explainable</h1><article className="empty"><h2>Read a round to inspect canonical history</h2><p>This app does not simulate balances, receipts, or finality.</p></article></>; }
function Help() { return <><h1>What MandateMesh does — and does not do</h1><article className="card"><h2>What is decided?</h2><p>Validators assess proposal coverage of locked mandates, not whether a plan was completed or endorsed.</p><h2>When is GEN available?</h2><p>Only after finality and canonical state reload, never at wallet signature.</p></article></>; }
function Shell() { const [modal, setModal] = useState(false); const [wallet, setWallet] = useState<WalletChoice | null>(null); const [account, setAccount] = useState<`0x${string}` | null>(null); return <><a className="skip" href="#main">Skip to content</a><Header account={account} onWallet={() => setModal(true)} />{modal && <WalletModal close={() => setModal(false)} connected={async (choice) => { setAccount(await connectWallet(choice.provider)); setWallet(choice); setModal(false); }} />}<main id="main"><Routes><Route path="/" element={<Home />} /><Route path="/rounds" element={<Rounds />} /><Route path="/rounds/new" element={<Start provider={wallet?.provider ?? null} account={account} />} /><Route path="/history" element={<History />} /><Route path="/help" element={<Help />} /></Routes></main></>; }
export default function App() { return <BrowserRouter><Shell /></BrowserRouter>; }
