import { useMemo } from 'react';
import { createClient } from 'genlayer-js';
import { studioDevnet } from 'genlayer-js/chains';
import { createTransactionKit, type Eip1193Provider } from '@genlayer/transaction-kit';

export type WalletChoice = { name: string; provider: Eip1193Provider };
type ProviderDetail = { info?: { name?: string }; provider: Eip1193Provider };
export const studioNext = { ...studioDevnet, name: 'GenLayer Studio Dev', rpcUrls: { default: { http: ['https://studio-next.genlayer.com/api'] } } };
export const contractAddress = import.meta.env.VITE_GENLAYER_CONTRACT_ADDRESS as `0x${string}` | undefined;

export function discoverWallets(): Promise<WalletChoice[]> { return new Promise((resolve) => { const wallets: WalletChoice[] = []; const add = (name: string, provider: Eip1193Provider) => { if (!wallets.some((item) => item.provider === provider)) wallets.push({ name, provider }); }; const receive = (event: Event) => { const detail = (event as CustomEvent<ProviderDetail>).detail; if (detail?.provider) add(detail.info?.name || 'Browser wallet', detail.provider); }; window.addEventListener('eip6963:announceProvider', receive); window.dispatchEvent(new Event('eip6963:requestProvider')); const injected = (window as Window & { ethereum?: Eip1193Provider & { providers?: Eip1193Provider[]; isMetaMask?: boolean; isRabby?: boolean; isOkxWallet?: boolean } }).ethereum; if (injected?.providers?.length) injected.providers.forEach((provider) => add('Injected wallet', provider)); else if (injected) add(injected.isRabby ? 'Rabby' : injected.isOkxWallet ? 'OKX Wallet' : injected.isMetaMask ? 'MetaMask' : 'Injected wallet', injected); window.setTimeout(() => { window.removeEventListener('eip6963:announceProvider', receive); resolve(wallets); }, 180); }); }
export async function connectWallet(provider: Eip1193Provider) { const chainId = `0x${studioNext.id.toString(16)}`; try { await provider.request({ method: 'wallet_switchEthereumChain', params: [{ chainId }] }); } catch (error) { if ((error as { code?: number }).code !== 4902) throw error; await provider.request({ method: 'wallet_addEthereumChain', params: [{ chainId, chainName: studioNext.name, nativeCurrency: studioNext.nativeCurrency, rpcUrls: studioNext.rpcUrls.default.http, blockExplorerUrls: ['https://explorer-studio-dev.genlayer.com/'] }] }); } const accounts = await provider.request({ method: 'eth_requestAccounts' }) as string[]; if (!accounts[0]) throw new Error('No account was selected.'); return accounts[0] as `0x${string}`; }
export function useMandateKit(provider: Eip1193Provider | null, account: `0x${string}` | null) { return useMemo(() => provider && account ? createTransactionKit({ chain: studioNext, provider, account }) : null, [provider, account]); }
export async function readRound(roundId: string) { if (!contractAddress) throw new Error('The Studio Dev contract address is not configured.'); const client = createClient({ chain: studioNext }); return client.readContract({ address: contractAddress, functionName: 'get_round', args: [roundId] }); }
